### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by philliphoff** [madskristensen/KnownMonikersExplorer#10]
**Is your feature request related to a problem? Please describe.**
I do much of my Visual Studio extension development in a Parallels hosted Windows VM on my M1 Mac, and miss having access to the various VSIX development related extensions.

**Describe the solution you'd like**
I'd like the extension to additionally target ARM64 versions of VS [2022].

**Describe alternatives you've considered**
When I really *need* these extensions I'll break down and RDP to my Windows desktop, but my VM runs so much snappier than RDP, even on the local network.

**Additional context**
For my own extension, I've found ARM64 support required only a small change to the VSIX manifest; no code changes were necessary (as it already targeted AnyCPU and did not make use of any AMD64-specific VS features).  I would guess this extension is similar.

**Comment by madskristensen** [comment]
Support added and published to the Marketplace

**Comment by philliphoff** [comment]
Just about to hit the "create PR button" to do the same.  Can't complain about the service. :-)
