### ISSUE TITLE
Exporting Light Mode images in Dark Mode, etc.

### ISSUE THREAD

**Issue by WithLithum** [madskristensen/KnownMonikersExplorer#11]
**Is your feature request related to a problem? Please describe.**
This extension exports images for the background of the current theme, and that means to export Light Background images you must switch to a theme that uses Light Background then export the image you want.

This will be useful if you are developing an app that uses, let's say, WinForms that cannot support dark background without massive custom rendering or by using third party libraries.

**Describe the solution you'd like**
To be able to select the image variant for Dark or Light background when exporting.

**Describe alternatives you've considered**
Switching between Light and Dark themes to export the image for the background you want.

**Additional context**
I have not worked on Visual Studio API and I am not sure if this is possible.

**Comment by madskristensen** [comment]
It's already doing that
