### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.Shell.Interop.15.6.DesignTime, Version=15.6.0.0'

### ISSUE THREAD

**Issue by reduckted** [madskristensen/KnownMonikersExplorer#4]
I just watched the latest episode of _Writing Visual Studio Extensions with Mads_ and saw that you had the same problem that I had recently with an extension failing to load because of this error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.Interop.15.6.DesignTime, Version=15.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

I solved it by installing the [`Microsoft.VisualStudio.Shell.Interop.15.6.DesignTime`](https://www.nuget.org/packages/Microsoft.VisualStudio.Shell.Interop.15.6.DesignTime/) NuGet package.

For some reason, the [`Microsoft.VisualStudio.SDK`](https://www.nuget.org/packages/microsoft.visualstudio.sdk) doesn't have a dependency on that particular package, but it does have dependencies on a bunch of other `Microsoft.VisualStudio.Shell.Interop.15.x.DesignTime` packages. 🤷‍♂️ 

```
Microsoft.VisualStudio.Shell.Interop.15.1.DesignTime (>= 16.9.31023.347)
Microsoft.VisualStudio.Shell.Interop.15.5.DesignTime (>= 16.9.31023.347)
Microsoft.VisualStudio.Shell.Interop.15.7.DesignTime (>= 16.9.31023.347)
Microsoft.VisualStudio.Shell.Interop.15.8.DesignTime (>= 16.9.31023.347)
Microsoft.VisualStudio.Shell.Interop.16.0.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.1.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.2.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.3.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.4.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.5.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.6.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.7.DesignTime (>= 16.9.31024.71)
Microsoft.VisualStudio.Shell.Interop.16.9.DesignTime (>= 16.9.31024.71) 
```

**Comment by madskristensen** [comment]
It was something similar that caused the issue, but I was able to figure it out and fix it. The issue was no `[ProvideCodeBase]` was added for the `Community.VisualStudio.Toolkit.dll`. That resulted in the VsTheme.cs XAML helper failed to load and that caused the initialization of the whole extension to fail. 

The fix was in the Toolkit code and I released an updated NuGet package

**Comment by MeisamSalehi** [comment]
I have the same problem with Visual Studio 2022
