### ISSUE TITLE
Access to the GUID/id representation required for VSCT files

### ISSUE THREAD

**Issue by drewnoakes** [madskristensen/KnownMonikersExplorer#8]
When editing a VSCT file we need a GUID/integer pair to describe the image. For example:

```xml
    <GuidSymbol name="ImageCatalogGuid" value="{ae27a6b0-e345-4288-96df-5eaf394ee369}">
      <IDSymbol name="Play" value="2356" />
    </GuidSymbol>
```

Using _KnownMonikers Explorer_ I can see I'd like to use `ResourceView`, however I cannot see the GUID or integer representation of these values.

Workarounds for this are to:

1. Use the legacy _Visual Studio Image Library Viewer_ and configure it to find the `.imagemanifest` file, and wait a long while for it to load everything, hoping it doesn't crash.
2. Open the `.imagemanifest` file manually to find the relevant entry for the moniker I'm interested in.

It'd be great to see the GUID/id in your extension. A context menu item to copy these values would be great.

![image](https://github.com/madskristensen/KnownMonikersExplorer/assets/350947/fa3d1772-afa2-4ce1-baf0-169451ca26dd)

If a _Copy VSCT data_ item could be added, it might copy text resembling this to the clipboard:

```xml
    <GuidSymbol name="ImageCatalogGuid" value="{ae27a6b0-e345-4288-96df-5eaf394ee369}">
      <IDSymbol name="ResourceView" value="2591" />
    </GuidSymbol>
```

**Comment by madskristensen** [comment]
You could also use the [VSCT IntelliSense extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsctIntelliSense2022). That's what I do
